from typing import Protocol
from uuid import UUID
from tinlance_agent_platform_domain import Assessment
class AssessmentRepository(Protocol):
    def get_by_idempotency(self,tenant_id:UUID,key:str)->Assessment|None: ...
    def create(self,assessment:Assessment)->Assessment: ...
    def get(self,tenant_id:UUID,assessment_id:UUID)->Assessment|None: ...
    def update(self,assessment:Assessment)->Assessment: ...